Добавив тест логування користувача,  поки не клікає на кнопку логін
qa-crash-course/opencart pull request #23
Opened 2020-11-16 11:25 UTC by TarasHrysiukk

Добавив тест логування користувача,  поки не клікає на кнопку логін у  пункті "My Account" на головній сторінці (тест зависає на цьому моменті)

2020-11-16 11:28 UTC, adomanich commented
> Добавив тест логування користувача, поки не клікає на кнопку логін у пункті "My Account" на головній сторінці (тест зависає на цьому моменті)

Це тому що у тебе там вейт закоментований

2020-11-16 11:31 UTC, adomanich requested changes

2020-11-16 11:31 UTC, adomanich commented on src/main/java/com/opencart/steps/MainPageBL.java
> +//    }
Будь ласка, видали закоментований код

2020-11-16 11:31 UTC, adomanich commented on src/main/java/com/opencart/steps/LoginPageBL.java
> +
Будь ласка, видали лишні пробіли і відворматуй код Ctrl+Alt+L

2020-11-16 11:31 UTC, adomanich commented on src/main/java/com/opencart/pages/SuccessLoginPage.java
> +
Будь ласка, видали зайвий пробіл

2020-11-16 15:49 UTC, NataliKinash commented on src/main/java/com/opencart/repository/LoginModelRepository.java
> +    public static LoginModel getLoginModel() {
Why did you use static here?

2020-11-16 15:52 UTC, NataliKinash commented on src/main/java/com/opencart/repository/LoginModelRepository.java
> +        String email = "test@gmail.com";
You can't hardcode input data in values. Use  System.getenv() or System.getProperty() instead

2020-11-16 15:56 UTC, NataliKinash commented on src/main/java/com/opencart/steps/LoginPageBL.java
> +        Assert.assertEquals(successLoginPage.getSuccessLoginTitle().getText(), expectedMessageLogin, "Incorrect page title");
It is better to save the actual result into String e.g.:
String actual = successLoginPage.getSuccessLoginTitle().getText()
ad then put saved string into assert, so it is more readable

2020-11-16 16:04 UTC, NataliKinash commented on src/main/java/com/opencart/pages/HeaderPage.java
> +        wait.until(ExpectedConditions.visibilityOf(loginButton));
try to use not only visibilityOf for each element, for the button you can put expected condition e.g elementToBeClickable​.
 Make sure an element is visible and enabled such that you can click it.

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html#elementToBeClickable(org.openqa.selenium.By)

2020-11-16 16:08 UTC, NataliKinash commented on opencart.iml
> +</module>
Add this file to .gitignore. This file is not needed in the project.

2020-11-20 17:16 UTC, qa-crash-course approved these changes

2020-11-20 17:19 UTC, Krynytsky approved these changes

2020-11-24 19:47 UTC, adomanich requested changes

2020-11-24 19:47 UTC, adomanich commented on src/main/java/com/opencart/driver/DriverRepository.java
> +        WebDriverManager.firefoxdriver().setup();
If you want to use Firefox, you can create a switch case, and take the browser name as a parameter of downloadWebDriver() method.

2020-11-24 19:47 UTC, adomanich commented on src/main/java/com/opencart/driver/DriverRepository.java
> +        webDriver = new FirefoxDriver();
If you want to use Firefox, you can create a switch case, and take the browser name as a parameter of instanceWebBrowser() method.

2020-11-24 19:47 UTC, adomanich commented on src/main/java/com/opencart/repository/LoginModelRepository.java
> +
please, remove extra space

2020-11-25 14:41 UTC, merged