Hrysiuk add new currency in admin
qa-crash-course/opencart pull request #28
Opened 2020-11-28 18:35 UTC by TarasHrysiukk

У AddNewCurrencyBL в методі registerNewCurrency 
не можу прописати  inputCodeCurrency(addNewCurrencyModel.getCurrencyCode());
 та 
inputValueCurrency(addNewCurrencyModel.getCurrencyValue());
просить зміти методи inputCodeCurrency та inputValueCurrency на int, якщо змінити то просить змінити на String.

2020-11-28 21:54 UTC, adomanich requested changes

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/datamodel/LoginAdminModel.java
> +
Please, remove extra space

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/datamodel/LoginAdminModel.java
> +
Please, remove extra space

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/datamodel/NewCurrencyModel.java
> +        }
Please, remove commented code

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/driver/DriverRepository.java
> +    private static String browserName = "Firefox";
Revert it to default (Chrome), if you wanna use Firefox, please do it localy

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/pages/AdminPage.java
> +    private WebElement currenciesButton;
Could you create a separate page and business logic for NavigationMenu functionality?

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/pages/AdminPage.java
> +    }
I think you need also create a separate CurrencyPage, for describing corresponding elements

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/repository/AddNewCurrencyRepository.java
> +       // int a = (int) Math.random();
Please, remove commented code

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/repository/AdminLoginRepository.java
> +
Please, remove extra spaces

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/steps/AdminPageBL.java
> +    }
You need to create a separate AdminLoginPageBL business class for this logic

2020-11-28 21:54 UTC, adomanich commented on src/main/java/com/opencart/steps/MainPageBL.java
> +    }
The admin page should not relate to MainPage in any ways

2020-11-28 21:54 UTC, adomanich commented on src/test/java/AddNewCurrencyTest.java
> +        Assert.assertEquals(1,1);
Could you describe the value of this assertion - Assert.assertEquals(1,1)?

2020-11-28 21:57 UTC, adomanich commented on src/main/java/com/opencart/datamodel/NewCurrencyModel.java
> +    private int currencyValue;
You can change is to string

2020-11-28 21:59 UTC, adomanich commented on src/main/java/com/opencart/steps/AddNewCurrencyBL.java
> +        inputValueCurrency(addNewCurrencyModel.getCurrencyValue());
Now it returns int, but inputCodeCurrency() should take a string

2020-11-29 13:01 UTC, TarasHrysiukk commented on src/test/java/AddNewCurrencyTest.java
> +        Assert.assertEquals(1,1);
this i wrote just to check if my test works

2020-11-29 13:02 UTC, TarasHrysiukk commented on src/test/java/AddNewCurrencyTest.java
> +        Assert.assertEquals(1,1);
я написав це лише для того, щоб перевірити, чи працює мій тест

2020-11-29 19:58 UTC, closed without merging